#!/bin/bash
#
# get-aws-route53-name-server-ips
#
# Copyright 2015, Alexander Jackson <alexander.jackson@jackson-it.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Uncomment to run in verbose mode
#set -x


# Vars
TMPFILE1=$(mktemp)
TMPFILE2=$(mktemp)


# Clear screen for usablity reasons
clear


# Intro
cat <<EOF


Get AWS Route 53 nameserver IP's and configure them for domains registered with Antagus

1. Go to https://console.aws.amazon.com/route53/home?region=XXXX#hosted-zones

2. Select domain

3. Copy nameserver list

4. Paste nameserver list next. (Finish with new line and continue with CTRL-D)


EOF


# Collect AWS nameserver list
NSLIST="$(</dev/stdin)"


# Save nameserver list to temporary file
echo "${NSLIST}" > ${TMPFILE1}


# Remove ending dot if present
sed -i 's/.$//g' ${TMPFILE1}


# Add header to ${TMPFILE2}
echo "Nameserver IPv4 IPv6" > ${TMPFILE2}
echo "---------- ---- ----" >> ${TMPFILE2}


# Clear screen for usablity reasons
clear


# Outro
cat <<EOF


5. Next, go to https://XXXX.antagus.de/create_ns and add these nameservers accordingly:

$(cat ${TMPFILE1} | while read line ; do IPV4=$(getent ahostsv4 ${line} | grep STREAM | awk '{ print $1 }') ; IPV6=$(getent ahostsv6 ${line} | grep STREAM
| awk '{ print $1 }') ; echo ${line} ${IPV4} ${IPV6} ; done >> ${TMPFILE2} ; column -t ${TMPFILE2})



6. Then visit https://XXXX.antagus.de/edit_domain and change the nameservers for your domain to:

$(cat ${TMPFILE1})



7. Done!


EOF


# Delete temporary files
rm ${TMPFILE1} ${TMPFILE2}
